# ml/src/categorization/taxonomy.py

CATEGORIES = [
    "Groceries",
    "Food & dining",
    "Transport",
    "Shopping",
    "Entertainment",
    "Utilities",
    "Bills",
    "Rent",
    "Loan / EMI",
    "Credit card payment",
    "Cash withdrawal / deposit",
    "Bank charges",
    "Interest",
    "Investment",
    "Insurance",
    "Salary / income",
    "Supplementary income",
    "Savings",
    "Travel",
    "Hotels",
    "Home improvement",
    "Services",
    "Fitness",
    "UPI transfer",
    "NEFT transfer",
    "IMPS transfer",
    "ACH / auto-debit",
    "Other",
]